language: node_js
node_js:
  - '0.12.2'
install:
  - npm cache clean
  - npm install
  - npm install -g yo
  - npm install -g .
  - npm install -g grunt-cli
  - npm install -g bower
script:
  - npm test
  - mkdir testAppDir && cd testAppDir
  - echo Yes | yo angular-blueprint myApp
  - echo | yo angular-blueprint:controller helloWorld
  - echo | yo angular-blueprint:directive foo
  - echo | yo angular-blueprint:factory bar
  - echo | yo angular-blueprint:filter baz
  - echo | yo angular-blueprint:route fooBar
  - echo | yo angular-blueprint:service barBaz
  - grunt
notifications:
  email:
    - dannybluedesign@gmail.com
