language: node_js
node_js:
  - '0.12.2'
script:
  - npm test
  - npm install -g yo
  - npm install -g .
  - touch  ~/.config/configstore/insight-yo.yml && echo "optOut:true" >> ~/.config/configstore/insight-yo.yml
  - mkdir testAppDir && cd testAppDir
  - yo angular-blueprint myApp
notifications:
  email:
    - dannybluedesign@gmail.com
