language: node_js
node_js:
  - '0.12.2'
  - '0.10.36'
install:
  - npm install
  - npm install -g yo
  - npm install -g .
  - npm install -g grunt-cli
  - npm install -g bower
script:
  - npm test
  - mkdir -p ~/.config/configstore/
  - echo "optOut":" true" > ~/.config/configstore/insight-yo.yml
  - mkdir testAppDir && cd testAppDir
  - yo angular-blueprint myApp
  - grunt
notifications:
  email:
    - dannybluedesign@gmail.com