language: node_js
node_js:
  - '0.12.2'
script:
  - npm test
  - npm install -g yo
  - npm install -g .
  - mkdir ~/.config/ && mkdir ~/.config/configstore/
  - touch ~/.config/configstore/insight-yo.yml
  - echo "optOut":" true" >> ~/.config/configstore/insight-yo.yml
  - cat ~/.config/configstore/insight-yo.yml
  - mkdir testAppDir && cd testAppDir
  - yo angular-blueprint myApp
  - grunt test
  - grunt build
notifications:
  email:
    - dannybluedesign@gmail.com
